name: locale_latlng
description: Get latitude and longitude from a country code.
version: 1.0.2
homepage: https://github.com/aloisdeniel/locale_latlng

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  http: ^0.13.0
