name: locale_latlng
description: Get country geocoordinates from a user locale, when geolocation isn't authorized.
version: 1.0.0
homepage: https://github.com/aloisdeniel/locale_latlng

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  http: ^0.13.0
